// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which transition an [`AlertEvent`] is, stripped of the observed value: the
 * form the controller persists in its alert history and hands to the
 * dashboard.
 */
export type AlertEventKind = "fired" | "still_firing" | "resolved";
