// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ClaimInvitationsResponse = { 
/**
 * Projects whose invitations now wait for the user to accept them.
 */
project_ids: Array<string>, };
