// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostName } from "./HostName";
import type { ProjectName } from "./ProjectName";
import type { ServiceName } from "./ServiceName";

export type ContainerStateResponse = { hostname: HostName, project_name: ProjectName, service_name: ServiceName, container_inspections: any, last_logs: string | null, last_updated: string, };
