// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeploymentId } from "./DeploymentId";
import type { DeploymentStatus } from "./DeploymentStatus";
import type { HostName } from "./HostName";
import type { ProjectName } from "./ProjectName";
import type { ServiceName } from "./ServiceName";

export type Deployment = { id: DeploymentId, digest: string, status: DeploymentStatus, service_id: bigint, created_at: string, service_name: ServiceName, project_name: ProjectName, hostname: HostName, };
