// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectInvitationResponse } from './ProjectInvitationResponse';

export type InviteToProjectResponse = {
	invitation: ProjectInvitationResponse;
	/**
	 * `false` when the address already had a pending invitation, in which
	 * case the caller should not send another invitation email.
	 */
	created: boolean;
};
