// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostName } from "./HostName";
import type { ProjectName } from "./ProjectName";
import type { ServiceName } from "./ServiceName";

export type LatestMetricResponse = { hostname: HostName, project_name: ProjectName, service_name: ServiceName, recorded_at: string, cpu_pct: number, mem_bytes: number, mem_limit_bytes: number, };
