// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MetricPointResponse = { recorded_at: string, cpu_pct: number, mem_bytes: number, mem_limit_bytes: number, };
