// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ServiceName } from './ServiceName';

/**
 * One service on a project tile: enough to render health and a name list
 * without shipping the full inspect blob.
 */
export type ProjectServiceSummary = {
	name: ServiceName;
	image: string | null;
	/**
	 * Docker's `State.Status`: created, running, paused, restarting,
	 * removing, exited or dead.
	 */
	status: string | null;
	/**
	 * Docker's `State.Health.Status` (starting, healthy, unhealthy) when the
	 * container defines a health check.
	 */
	health: string | null;
	started_at: string | null;
	restart_count: number;
};
