// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Latest resource usage summed over the project's current services.
 */
export type ProjectMetricsSummary = { cpu_pct: number, mem_bytes: number, mem_limit_bytes: number, recorded_at: string, };
