// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Deployment } from "./Deployment";
import type { HostName } from "./HostName";
import type { ProjectMetricsSummary } from "./ProjectMetricsSummary";
import type { ProjectName } from "./ProjectName";
import type { ProjectRole } from "./ProjectRole";
import type { ProjectServiceSummary } from "./ProjectServiceSummary";

export type ProjectSummaryResponse = { id: string, name: ProjectName, hostname: HostName, 
/**
 * The calling user's role, not the project's.
 */
role: ProjectRole, created_at: string, 
/**
 * When the agent last reported this project; `None` if it never did.
 */
last_updated: string | null, services: Array<ProjectServiceSummary>, 
/**
 * Most recent rollout attempt (success, failure or rollback).
 */
latest_deployment: Deployment | null, metrics: ProjectMetricsSummary | null, pending_updates: number, member_count: number, notifier_count: number, };
