// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectInvitationResponse = { id: string, email: string, 
/**
 * The invitee's account once known; `None` while waiting for them to
 * sign up.
 */
user_id: string | null, invited_by: string, created_at: string, };
