// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectInvitationResponse } from './ProjectInvitationResponse';
import type { ProjectMemberResponse } from './ProjectMemberResponse';
import type { ProjectSummaryResponse } from './ProjectSummaryResponse';

export type ProjectDetailResponse = {
	project: ProjectSummaryResponse;
	/**
	 * The owner first, then the co-maintainers.
	 */
	members: Array<ProjectMemberResponse>;
	invitations: Array<ProjectInvitationResponse>;
};
