// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProjectRole } from './ProjectRole';

export type ProjectMemberResponse = {
	user_id: string;
	role: ProjectRole;
	invited_by: string | null;
	created_at: string;
};
