// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a user is to a project. The owner is the account whose agent reports
 * the project (`project.user_id`); members were invited to co-maintain it.
 */
export type ProjectRole = 'owner' | 'member';
