// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ProjectInvitationResponse = {
	id: string;
	email: string;
	invited_by: string;
	created_at: string;
};
