// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostName } from "./HostName";
import type { ProjectName } from "./ProjectName";

/**
 * An invitation waiting for the calling user's answer.
 */
export type ReceivedInvitationResponse = { id: string, project_id: string, project_name: ProjectName, hostname: HostName, invited_by: string, created_at: string, };
