// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Which figure of a [`ContainerMetricSample`] an alert rule watches.
 */
export type AlertMetric = "cpu_pct" | "mem_pct" | "mem_bytes";
