// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlertMetric } from "./AlertMetric";

/**
 * Wire shape of one metric alert rule for the dashboard. Rules carry no
 * secrets, so unlike notifiers the full row is returned.
 */
export type AlertRuleResponse = { id: string, metric: AlertMetric, threshold: number, for_seconds: number, cooldown_seconds: number, hostname: string | null, project: string | null, service: string | null, enabled: boolean, created_at: string, };
