// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlertEventKind } from "./AlertEventKind";
import type { AlertMetric } from "./AlertMetric";

/**
 * Wire shape of one recorded alert transition for the dashboard's history.
 */
export type AlertEventResponse = { id: string, 
/**
 * `null` once the rule behind this entry has been deleted.
 */
rule_id: string | null, kind: AlertEventKind, metric: AlertMetric, threshold: number, 
/**
 * The reading that produced the transition, in the metric's unit.
 */
value: number, for_seconds: number, hostname: string, project: string, service: string, triggered_at: string, 
/**
 * Whether this entry arrived since the user's previous login.
 */
is_new: boolean, };
