// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlertEventResponse } from "./AlertEventResponse";

/**
 * Wire shape of GET /alerts/events: the history plus what counts as new.
 */
export type AlertHistoryResponse = { 
/**
 * Newest first.
 */
events: Array<AlertEventResponse>, 
/**
 * Start of the previous login session; `null` on a first-ever login,
 * where nothing is marked new.
 */
new_since: string | null, new_count: number, };
