// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AlertMetric } from "./AlertMetric";

/**
 * Body of POST /alerts. Empty scope strings are treated as "any", so the
 * dashboard can send its form state as-is.
 */
export type CreateAlertRuleBody = { metric: AlertMetric, threshold: number, for_seconds: number, cooldown_seconds: number, hostname: string | null, project: string | null, service: string | null, };
