// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { LatestMetricResponse } from "./LatestMetricResponse";

export type LatestMetricsResponse = Array<LatestMetricResponse>;
