// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeploymentId } from "./DeploymentId";
import type { DeploymentStatus } from "./DeploymentStatus";
import type { HostName } from "./HostName";
import type { ProjectName } from "./ProjectName";
import type { ProjectRole } from "./ProjectRole";
import type { ServiceName } from "./ServiceName";

/**
 * One row of the deployments list across all accessible projects: the
 * deployment plus the project it belongs to, so the dashboard can link to
 * the project-scoped pages (which also work for shared projects).
 */
export type ProjectDeploymentResponse = { project_id: string, 
/**
 * The calling user's role in that project.
 */
role: ProjectRole, id: DeploymentId, digest: string, status: DeploymentStatus, service_id: string, created_at: string, service_name: ServiceName, project_name: ProjectName, hostname: HostName, 
/**
 * Redacted log tail captured on rollback/failure; `None` otherwise.
 */
logs: string | null, };
