// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { HostName } from "./HostName";
import type { MetricPointResponse } from "./MetricPointResponse";
import type { ProjectName } from "./ProjectName";
import type { ServiceName } from "./ServiceName";

export type ServiceMetricsResponse = { hostname: HostName, project_name: ProjectName, service_name: ServiceName, points: Array<MetricPointResponse>, };
